### ISSUE TITLE
Please, close this issue.

### ISSUE THREAD

**Issue by ghost** [emchristiansen/OpenCVJavaDemo#1]
Please, close this issue.

**Comment by emchristiansen** [comment]
I don't maintain this code.

That said, it looks like the .jar doesn't have the names you're expecting.
You can inspect a .jar's symbols using jnm: https://github.com/daviddrysdale/jnm

Or you might just follow the OpenCV guide here: http://docs.opencv.org/doc/tutorials/introduction/desktop_java/java_dev_intro.html
Hopefully it will be up to date.
